<a href="https://colab.research.google.com/github/Revano512/learn_ml/blob/main/00_pytorch_fundamentals_revano.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using `torch.Tensor()` = https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html


In [ ]:
# scalar
scalar = torch.tensor(10)
scalar

tensor(10)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

10

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim     # the number of closing brackets

1

In [ ]:
vector.shape    # total of 2 elements

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
print(MATRIX.ndim)

print(MATRIX.shape)

2
torch.Size([2, 2])


In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

print(TENSOR.ndim)
print(TENSOR.shape)   # we have 1 dimension of 3-by-3

3
torch.Size([1, 3, 3])


### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
print(random_tensor)
print(random_tensor.ndim)

tensor([[0.9306, 0.2330, 0.6972, 0.4789],
        [0.2791, 0.8915, 0.5719, 0.5898],
        [0.5221, 0.0326, 0.4386, 0.5503]])
2


In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

Zeros and ones

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# use torch.arange()
stuff = torch.arange(start=1,end=110,step=5)

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=stuff)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False
                               )

float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors are not the right datatype - to do get datatype from a tensor, can use tensor.dtype

2. Tensors are not the right shape - to get shape from a tensor, can use tensor.shape

3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [ ]:
# Find out details about some tensor
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9891, 0.0584, 0.9369, 0.3412],
        [0.6735, 0.9404, 0.1021, 0.1407],
        [0.1591, 0.5489, 0.9435, 0.5656]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10
print(tensor)

# Multiply tensor by 10
tensor = tensor * 10
print(tensor)

# In-built functions
torch.mul(tensor, 10)
print(tensor)

torch.add(tensor, 10)
print(tensor)

tensor([1, 2, 3])
tensor([10, 20, 30])
tensor([10, 20, 30])


tensor([20, 30, 40])

### Matrix multiplication

2 ways:
1. Element-wise multiplication
2. Matrix multiplication (dot product) - rows & columns

rules:
1. Inner dimension must match
2. The resulting matrix has the shape of the outer dimensions


In [ ]:
# Element-wise

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

# Matrix mul

print(torch.matmul(tensor, tensor))

### One of the most common errors in deep learning: shape errors



In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

# torch.mm() is the same as torch.matmul()
# torch.mm(tensor_A, tensor_B)  will lead to error, so we use transpose

# transpose: switch axes
print(tensor_B.T, tensor_B.T.shape)

torch.mm(tensor_A, tensor_B.T)

tensor([[ 7,  8,  9],
        [10, 11, 12]]) torch.Size([2, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min,max,mean,sum,etc (tensor aggregation)

In [ ]:
# Create tensor
x = torch.arange(0,100,10)

# min
torch.min(x), x.min()

# max
torch.max(x), x.max()

# mean; note: the torch.mean() function requires a tensor of float32
# datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

# sum
torch.sum(x), x.sum()


(tensor(45.), tensor(45.))

### Finding the positional min and max

Basically, find which position the min or max is at in the tensor

In [ ]:
# position of min
x.argmin()

# position of max
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing, unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined short
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions premuted (swapped) in a certain way

In [ ]:
# create tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

# !Changing z changes x!

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
print(x_stacked)

print(x_reshaped.squeeze())
print(x_reshaped.squeeze().shape)
print(x_reshaped.shape)                 # squeeze removes all single dimensions from a target tensor

print("------------")
print(x_reshaped.unsqueeze(dim=0))
print(x_reshaped.unsqueeze(dim=0).shape)        # unsqueeze adds a single dimension to a target tensor at a specific dim


x_original = torch.rand(size=(224,224,3))     # height, width, color_channels

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2,0,1)
print("-------------")
print(x_original.shape)
print(x_permuted.shape)         # permute changes the position of the dimensions; here, shifts axis 0->1, 1->2, 2->0
# important, if you change x_original, the value of x_permuted will also change, because it takes the same place in memory


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([9])
torch.Size([1, 9])
------------
tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])
torch.Size([1, 1, 9])
-------------
torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
print(x, x.shape)

print("-----1")
# Index on new tensor
print(x[0])
print(x[0][0])
print(x[0][0][0])

print("-----2")

# You can also use ":" to select "all" of a target dimension
print(x[:,0])
print(x[:,:,1])


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
-----1
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)
-----2
tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor(9)


### PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library.
PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
print(f"{array}\n{tensor}")

# Note: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64

# Also note: even if you change the value of the array, you won't change the value of the tensor

[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

# the default datatype of numpy is float64, whereas for pytorch it's float64
tensor = tensor + 1
print(tensor, numpy_tensor)

tensor([2., 2., 2., 2., 2., 2., 2.]) [1. 1. 1. 1. 1. 1. 1.]


### Reproducibility (trying to take random out of random)

In short, how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness

In [ ]:
import torch

# create 2 random tensors
random_tensor_A = torch.rand(10, 10)
random_tensor_B = torch.rand(10, 10)
#print(random_tensor_A)
#print(random_tensor_B)
same_randvalue = random_tensor_A == random_tensor_B
print(same_randvalue)

any_true = torch.any(same_randvalue == True)

if any_true == True:
  print("True")
  result = torch.where(random_tensor_A == random_tensor_B)
  print(result)
  print(random_tensor_A[result])
else:
  print("False")

# Set the random seed with torch.manual_seed(RANDOM_SEED)
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(10, 10)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(10, 10)

print(random_tensor_C == random_tensor_D)


tensor([[False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False]])
False
tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, Tr

### Running tensors and pytorch objects on the gpus (and making faster computations)

GPU = faster computation on numbers, thanks to cuda + nvidia hardware + pytorch working bts

### 1. Getting a GPU

1. Easiest - use google coab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options...
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2 and 3, refer to pytorch documentations: https://pytorch.org/get-started/locally/



### Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

Since pytorch can run on the cpu or gpu, this is best practice:
https://pytorch.org/docs/stable/notes/cuda.html

E.g. run on GPU in available, if else default to cpu

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [ ]:
# create a tensor(default on the CPU)
tensor = torch.tensor([1,2,3,])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu # will display the index and the gpu which is being used

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
#tensor_on_gpu.numpy()

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')